#!/bin/bash
echo "Hi I am Shibnath Chakraborty"
echo "we are learning github"
echo "Sabka sath sabka vikash"
echo "Add from new branch from visual studio"
echo "today we are again learing on visual code"
echo "me and prashant now working on it"